-- +migrate Up
CREATE TABLE users (
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR  NOT NULL,
  age INTEGER NOT NULL,
  type INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()

);

CREATE TABLE items (
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR  NOT NULL,
  user_id INTEGER REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE, 
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- +migrate Down
DROP TABLE items;
DROP TABLE users;